export type MaybePromise<T> = T | Promise<T>;

export interface ChatGateBusinessUnit {
  id: string;
  externalId: string;
  name: string;
  type: string;
  isActive?: boolean;
}

export interface ChatGateSession {
  accessToken: string;
  organizationId: string;
  userId: string;
  conversationId?: string;
  businessUnitId?: string | null;
  businessUnits?: ChatGateBusinessUnit[];
  channel?: string;
  /** Unix epoch milliseconds. When omitted, the SDK reads the JWT exp claim. */
  expiresAt?: number;
}

export interface ChatGateSessionContext {
  forceRefresh: boolean;
  businessUnitExternalId?: string;
}

export type ChatGateSessionProvider = (
  context: ChatGateSessionContext,
) => Promise<ChatGateSession>;

export interface ChatGateUser {
  id: string;
  username: string;
  email?: string | null;
  phoneNumber?: string | null;
  avatarUrl?: string | null;
  lastSeenAt?: string | null;
}

export interface ChatGateReaction {
  emoji: string;
  userId: string;
}

export type ChatGateMessageType = "text" | "image" | "file" | "voice" | "encrypted";

export interface ChatGateMessage {
  id: string;
  content: string;
  messageType: ChatGateMessageType;
  fileUrl?: string | null;
  fileName?: string | null;
  fileMimeType?: string | null;
  fileSize?: number | null;
  fileDurationMs?: number | null;
  replyToId?: string | null;
  replyTo?: ChatGateMessage | null;
  senderId: string;
  receiverId: string;
  inboxConversationId?: string | null;
  sender?: ChatGateUser;
  receiver?: ChatGateUser;
  reactions?: ChatGateReaction[];
  read: boolean;
  createdAt: string;
  clientMessageId?: string | null;
  encryptionVersion?: number;
  ciphertext?: string | null;
  [key: string]: unknown;
}

export type ChatGateConversationStatus = "OPEN" | "PENDING" | "RESOLVED";

export interface ChatGateConversation {
  id: string;
  status: ChatGateConversationStatus;
  priority?: "LOW" | "NORMAL" | "HIGH" | "URGENT" | string;
  subject?: string | null;
  createdAt: string;
  lastMessageAt: string;
  customerId?: string;
  assigneeId?: string | null;
  customer?: ChatGateUser | null;
  assignee?: ChatGateUser | null;
  createdBy?: ChatGateUser | null;
  businessUnit?: ChatGateBusinessUnit | null;
  unreadCount?: number;
  messageCount?: number;
}

export interface ChatGateConversationThread extends ChatGateConversation {
  messages: ChatGateMessage[];
  nextCursor?: string | null;
  [key: string]: unknown;
}

export interface ChatGateConversationState {
  conversationId?: string;
  thread?: ChatGateConversationThread;
  messages: ChatGateMessage[];
  onlineUserIds: string[];
  typingUsers: ChatGateTypingEvent[];
  loading: boolean;
  loadingOlder: boolean;
  sending: boolean;
  uploading: boolean;
  error: Error | undefined;
}

export interface ChatGateConversationFilters {
  status?: ChatGateConversationStatus;
  businessUnitId?: string;
}

export interface ChatGateSendMessageInput {
  conversationId?: string;
  content?: string;
  messageType?: Exclude<ChatGateMessageType, "encrypted">;
  fileUrl?: string;
  fileName?: string;
  fileMimeType?: string;
  fileSize?: number;
  fileDurationMs?: number;
  replyToId?: string;
  /** Generated by the SDK when omitted. */
  clientMessageId?: string;
}

export interface ChatGateUploadFile {
  /** Browser File/Blob, or a React Native { uri, name, type } object. */
  value: unknown;
  name?: string;
  mimeType?: string;
}

export interface ChatGateUploadResult {
  url: string;
  fileName: string;
  mimeType: string;
  size: number;
  durationMs?: number;
}

export interface ChatGateTypingEvent {
  userId: string;
  username?: string;
  isTyping: boolean;
}

export interface ChatGatePresenceEvent {
  userIds: string[];
}

export interface ChatGateReadEvent {
  readerId: string;
  senderId: string;
}

export interface ChatGateMessageDeletedEvent {
  messageId: string;
  senderId?: string;
  receiverId?: string;
}

export interface ChatGateMessageReactionsEvent {
  messageId: string;
  senderId?: string;
  receiverId?: string;
  reactions: ChatGateReaction[];
}

export interface ChatGateRequestInit {
  method?: string;
  headers?: Record<string, string>;
  body?: unknown;
}

export interface ChatGateResponse {
  readonly ok: boolean;
  readonly status: number;
  json(): Promise<unknown>;
  text(): Promise<string>;
}

export type ChatGateFetch = (
  url: string,
  init?: ChatGateRequestInit,
) => Promise<ChatGateResponse>;

export interface ChatGateSocket {
  connected: boolean;
  auth: Record<string, unknown>;
  connect(): ChatGateSocket;
  disconnect(): ChatGateSocket;
  on(event: string, listener: (...args: unknown[]) => void): ChatGateSocket;
  off(event: string, listener?: (...args: unknown[]) => void): ChatGateSocket;
  emit(event: string, ...args: unknown[]): ChatGateSocket;
}

export type ChatGateSocketFactory = (
  socketUrl: string,
  accessToken: string,
) => ChatGateSocket;

export interface ChatGateLogger {
  debug?(message: string, details?: unknown): void;
  warn?(message: string, details?: unknown): void;
  error?(message: string, details?: unknown): void;
}

export interface ChatGateClientOptions {
  /** Host only, without /api. Example: https://api.chat-gate.com */
  baseUrl: string;
  socketUrl?: string;
  /** Advanced authentication hook for private, application-owned sessions. */
  sessionProvider?: ChatGateSessionProvider;
  /** Browser-safe publishable key. Never use a cg_live_ key here. */
  publicKey?: string;
  organizationId?: string;
  /** Stable customer/visitor identifier sent as externalUserId. */
  userId?: string;
  userName?: string;
  /** Optional HMAC produced by your server for a verified signed-in user. */
  userHash?: string;
  channel?: string;
  roomId?: string;
  businessUnitExternalId?: string;
  fetch?: ChatGateFetch;
  socketFactory?: ChatGateSocketFactory;
  logger?: ChatGateLogger;
  refreshLeewayMs?: number;
  sendTimeoutMs?: number;
}

export interface ChatGateEventMap {
  session: ChatGateSession;
  connected: undefined;
  disconnected: { reason?: string };
  connectionError: unknown;
  embedReady: { conversationId: string };
  message: ChatGateMessage;
  messageUpdated: ChatGateMessage;
  messageDeleted: ChatGateMessageDeletedEvent;
  messageReactions: ChatGateMessageReactionsEvent;
  typing: ChatGateTypingEvent;
  presence: ChatGatePresenceEvent;
  read: ChatGateReadEvent;
  resync: { reason: string; missed: number };
  error: Error;
}

export type ChatGateEventName = keyof ChatGateEventMap;
export type ChatGateEventListener<K extends ChatGateEventName> = (
  value: ChatGateEventMap[K],
) => void;
